version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"   
    depends_on:
      - db  
      - redis   
    environment:
      - NGINX_HOST=localhost
      - QUEUE_CONNECTION=redis   

  db:
    image: mysql:8.4  
    environment:
      - MYSQL_DATABASE=news
      - MYSQL_USER=mikel
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3307:3306"   
    volumes:
      - "./db:/docker-entrypoint-initdb.d"  

  nginx:
    image: nginx:1.27   
    volumes:
      - "./:/var/www/html"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - app

  redis:
    image: redis:7.4   
    ports:
      - "6380:6379"

  laravel-queue-worker:
    build:
      context: .  
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"  
    depends_on:
      - db
      - redis
    command: /bin/sh -c "while ! mysqladmin ping -h db --silent; do sleep 20; done && php artisan queue:work --queue=default --sleep=60 --tries=2 --timeout=300"
    restart: always  

  laravel-scheduler:
    build:
      context: .  
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"  
    command: /bin/sh -c "while ! mysqladmin ping -h db --silent; do sleep 20; done && while true; do php artisan schedule:run >> /var/www/html/storage/logs/scheduler.log 2>&1; sleep 60; done"
    restart: always  
